[project]
name = "loan-approval-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "lab>=8.2",
    "fastai>=2.7.17",
    "scikit-learn>=1.5.2",
]
